???

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -29,7 +29,18 @@ function status() {
 }
 
 function start() {
+    if (is_running); then
+	echo "Neo4J server is already started";
+        exit 0
+    fi
+
     ${NEO4J_BIN_DIR}/neo4j start -host $OPENSHIFT_NEO4J_DB_HOST -port $OPENSHIFT_NEO4J_DB_PORT
+
+    ret=$?
+    if [ $ret -ne 0 ]; then
+        echo "Neo4j failed to start - $ret" 1>&2
+        exit $ret
+    fi
 }
 
 function stop() {
